apiVersion: v1
data:
    password: ENC[AES256_GCM,data:Egqat3gKJCrSomcNLL+HDg==,iv:2TUvmJQ2knGaPE5OFwjXCnIcHHiI+8KLXZPbjH5Lnsg=,tag:3lvf9VHvGypsIKR3cGYZVw==,type:str]
    username: ENC[AES256_GCM,data:y9/+Ow==,iv:H+IzwN1J0UCN2+mlXeWSSDD6Kfzlo4AfHs2LgwJa5ig=,tag:21+sbMOSSe2HK4W8n7W62g==,type:str]
kind: Secret
metadata:
    name: nexus-push
    namespace: dhole
    annotations:
        sync.kuvryn.io/prune: disabled
    labels:
        app.kubernetes.io/managed-by: kuvryn-sync
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncnV6UkZyeVhSTUQrMjF0
            WGdxcTR2cHZxTk1LQ0ZGV3Z3MWlhRGdrRDBNCkxocmsrb0tva2tCTllVSnRnMHdJ
            U3VMaEtnL0tyS0NFVCtpUXErZ1lrZkEKLS0tIGtFVGlNTWNzWE1ZdEJObHp2ZDhw
            cUlFajdKbVp1Z3FuczA2Zm1nNDhsdDQK03KEfz4T52VA8SmS5wxjeZf8fnvqgbei
            a3zomYH4n4A55/dR4n3uaoqpjNENR25VbpJ3dcWuxyJYJE+JvI4CXQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cf6eeuly2m5gk376r7lw5psvxq8ufrsxgukhddwpeszw3m4q445qy83nqn
    encrypted_regex: ^(data|stringData|env)$
    lastmodified: "2026-09-27T13:59:17Z"
    mac: ENC[AES256_GCM,data:pYeeJbJBQcQ4/4KsCkaJbYE6lq3xMPHp6z1VMVdjX8KPWGbHZ9HWw/1sNZKDGVC++o/oDQ1RW3e275BFS3zdOVbxm6pWQkkAm1FPT16PcAvpcotOnJdQkhqkaU5wYlVZAZqu/Wg8MuK77pO0Nb25XyasxHuqCRInhEYp3vdQ3BI=,iv:olM0alUEiy8VvVWH6gpCiNHPKgpoLOWRD1J4ysKf/8o=,tag:0t7gXB4AD2Vkm+vOLDvLag==,type:str]
    version: 3.13.3
