apiVersion: v1
data:
    dsn: ENC[AES256_GCM,data:TXu8XEYA/hsy2v/a8hGtBR4AGrDTzFZZNyHl/+vUU0kfS6J+LOZFuWt39pzZvYnDerGMWUsUk3vVWrGbJMJA4EsIrW26v7x5l0P1DXWljDYakPIXLXS6SJG0N9wnpq7cDzTlVVp/hbHBY3xAB1VJlJg9ru/VxRT94tCQXQ==,iv:rQR8sdDqQAZ+VtMmHVqaAtJOre7JAb+gq+u2fjFoyd4=,tag:lsuurkQtSdKCZPxW2lfF8w==,type:str]
    password: ENC[AES256_GCM,data:hkdrCga1CTh4k+GWL0GrAuGdklwUGnXd6PsWRKbQD1Hkr9/jixEYw+awl+g=,iv:axkIUtykA4j46bs/tUxTz+vRSmC3f/q4foBtlof4Z/U=,tag:S5UNJ2LU9YtB7mqCgvo1fQ==,type:str]
kind: Secret
metadata:
    name: dhole-store
    namespace: dhole
    labels:
        app.kubernetes.io/instance: dhole
        app.kubernetes.io/managed-by: kuvryn-sync
        app.kubernetes.io/name: dhole
        app.kubernetes.io/version: 0.1.0
        helm.sh/chart: dhole-0.1.0
    annotations:
        sync.kuvryn.io/prune: disabled
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkTVhIdzdaVHpTLzNDbFBu
            bDVhYlFpUWEvRk9jUWFSV3dPVDRSL3E5cVNvCkJjTHdVa0dacDdrMWNmRkN0K2Qz
            NEMzdHVmaUNzTFhSSVh6ZkVwQXZ3OG8KLS0tIHc0RVUyWHlIRFA2ZnRlV0s0bXhE
            V2hkOEFIUnRkTWRDZmRFSEM0aHlvaVEKcJjZgUP/R2mMmFrBgRjR8Zrb29mW8S+f
            oF1G+UOXrfZgnRgCHdYg94Wqi1pHaEuZN2bYZtMcxRUYuBmozxna+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cf6eeuly2m5gk376r7lw5psvxq8ufrsxgukhddwpeszw3m4q445qy83nqn
    encrypted_regex: ^(data|stringData|env)$
    lastmodified: "2026-09-27T13:59:17Z"
    mac: ENC[AES256_GCM,data:JE4ZRCZpENGegCHSKhT617Im171zr4gs+oMkvy73/tv7crDHiqAAL3v4COAVjSQXIxxjNVThCczqW5o5mqFItbKaV7zrICs331YSRk65enmP2zkd2U5+SFIXnovYo55N+Xf5Pd5PoWypTzCaEu2PyO6dzkawOBAuSe+Vd75PxW4=,iv:Txs0jWtXJtfp5YC1xH76PIqYcgBfOZuzVMBjI1fRvxU=,tag:rGjU9MV3l3cV2AhVWWRaEA==,type:str]
    version: 3.13.3
