apiVersion: v1
data:
    accessKeyId: ENC[AES256_GCM,data:m9rwAP2b7S4HohnM,iv:X0wNGPGV7uO12XvTI0aWosdsPt8jZNI0DNXr9+xr32g=,tag:qe4ca8W3Op3MeUZxHz2aSQ==,type:str]
    secretAccessKey: ENC[AES256_GCM,data:jT+sqGCaJRzcn+KMj8GCBVORa5Y=,iv:0sA58ge31b/WXIhinS/c95WteGKd4nQ6uiqNqSqY7es=,tag:3mRKX6PNT37hkCcnBOmAGg==,type:str]
kind: Secret
metadata:
    name: dhole-s3
    namespace: dhole
    annotations:
        sync.kuvryn.io/prune: disabled
    labels:
        app.kubernetes.io/managed-by: kuvryn-sync
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMFIvS0FHeExoVTgzQTZn
            TDkrWWV6QWxuQ1ZYb2cyajZ1ZUx0dXRXOFNBCkRETmRzRjIzQUpHOG5oekd2T2tp
            NTZjdzFDK3hjcUVDSmcyVXRzZ3dCU1EKLS0tIGNzZ0hpdWFLTjljejh1MGQzTmFz
            elJ1dkRZYnBKeFhvaXJXblB4YUtYbXcKQ5T2LMkd4a1cElBP6tS4XPNBYXddQSKn
            8Jt6CEbV3yh/6/BWlkwbD/dBdijTsiAmpZpDK2qmDL0DsVkBfSpeKA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cf6eeuly2m5gk376r7lw5psvxq8ufrsxgukhddwpeszw3m4q445qy83nqn
    encrypted_regex: ^(data|stringData|env)$
    lastmodified: "2026-09-27T13:59:17Z"
    mac: ENC[AES256_GCM,data:c+YU3taI1YguEkjO4KHhlx0qPcCqWjVSTWbr9ks1MGqbnIOQ6RRpEonxxwsDtiSDRMgQZIfhEjVBZthUEJVyHLk4v7khpWsNx9EXBXQTjPrkWoZ4mAMaaV1VER1ISmthtS7t79ojvfr6Z4Q3cTOvuTKg9DTkb9e+sRD71q++wuY=,iv:p+YAWXq58W//fRiZSkloe3DCBirpFM7B6j7+h38A804=,tag:U2uQX5KeOMpR4MooETXvNA==,type:str]
    version: 3.13.3
